<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260213151130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_path VARCHAR(255) NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF5A5CF639F774 ON asset (campaign_id)');
        $this->addSql('CREATE TABLE campaign (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, video_config JSON DEFAULT NULL, financial_goal NUMERIC(12, 2) NOT NULL, current_amount NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE donor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7F24097E7927C74 ON donor (email)');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(50) NOT NULL, stripe_payment_intent_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, donor_id INT NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_723705D1FC72F97E ON transaction (stripe_payment_intent_id)');
        $this->addSql('CREATE INDEX IDX_723705D13DD7B7A7 ON transaction (donor_id)');
        $this->addSql('CREATE INDEX IDX_723705D1F639F774 ON transaction (campaign_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_campaign (user_id INT NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (user_id, campaign_id))');
        $this->addSql('CREATE INDEX IDX_FF98F6DDA76ED395 ON user_campaign (user_id)');
        $this->addSql('CREATE INDEX IDX_FF98F6DDF639F774 ON user_campaign (campaign_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D13DD7B7A7 FOREIGN KEY (donor_id) REFERENCES donor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_campaign ADD CONSTRAINT FK_FF98F6DDA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_campaign ADD CONSTRAINT FK_FF98F6DDF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5CF639F774');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D13DD7B7A7');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1F639F774');
        $this->addSql('ALTER TABLE user_campaign DROP CONSTRAINT FK_FF98F6DDA76ED395');
        $this->addSql('ALTER TABLE user_campaign DROP CONSTRAINT FK_FF98F6DDF639F774');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('DROP TABLE donor');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_campaign');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
